# Generated by Django 4.2.16 on 2024-11-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0003_alter_parcel_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='tracking_number',
            field=models.CharField(default='CG9QHCDNBJ', max_length=100, unique=True),
        ),
    ]
