# Generated by Django 4.2.16 on 2024-11-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0007_alter_parcel_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='tracking_number',
            field=models.CharField(default='FZ71M6J3L6', max_length=100, unique=True),
        ),
    ]
