# Generated by Django 4.2.16 on 2025-04-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entry", "0010_user_is_active_alter_parcel_tracking_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parcel",
            name="tracking_number",
            field=models.CharField(default="EBA15XO7SU", max_length=100, unique=True),
        ),
    ]
