# Generated by Django 4.2.16 on 2024-11-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='sender_contact',
            field=models.CharField(default='+254771178496', max_length=15),
        ),
    ]
