# Generated by Django 4.2.16 on 2024-11-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0002_parcel_sender_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='expected_arrival',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
