# Generated by Django 4.2.16 on 2024-11-13 18:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('vehicle_registration', models.CharField(max_length=50, unique=True)),
                ('area_of_operation', models.CharField(max_length=100)),
                ('current_location', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(max_length=60)),
                ('role', models.CharField(default='rider', max_length=20)),
                ('status', models.CharField(default='available', max_length=20)),
            ],
        ),
    ]
