# Generated by Django 4.2.16 on 2024-11-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
